### ISSUE TITLE
Loading Process Multiimage

### ISSUE THREAD

**Issue by junoprima** [jirawatee/FirebaseStorage-Android#2]
Hi I need to upload with multi photo but on process dialog got 100 % not loading another image 
how i solve it

**Comment by jirawatee** [comment]
You can add multiple files to UploadTask then .addOnProgressListener() will handle them for you automatically.

For example
mUploadTask = imageRef1.putFile(file1);
mUploadTask = imageRef2.putFile(file2);
mUploadTask = imageRef3.putFile(file3);
