### ISSUE TITLE
Can't upload image to storage because of IllegalStateException: Task is not yet complete

### ISSUE THREAD

**Issue by odai-alquhaly** [jirawatee/FirebaseStorage-Android#3]
I didn't have this issue before i think it appeared after i upgraded my firebase dependencies.
my current storage dependency is 16.0.1

**Comment by jirawatee** [comment]
Sorry for my late reply.
I just fixed how to get download url from getDownloadUrl() and also upgrade SDK to v16.1.0
Please pull it and try again.
